#!/usr/bin/env bash
#

# Detect distribution and set package manager
if command -v apt >/dev/null 2>&1; then
	package_manager="apt install -y"
elif command -v yum >/dev/null 2>&1; then
	package_manager="yum install -y"
elif command -v pacman >/dev/null 2>&1; then
	package_manager="pacman"
	opts=(-Sy --noconfirm)
else
	echo "Error: Unhandled distribution"
	exit 1
fi

# Array of packages
packages=(curl git neo-vim noto-fonts-emoji ttf-fira-code fzf fd nvm)

# Install Packages
for package in "${packages[@]}"; do
	echo "Install $package using $package_manager"
	sudo "$package_manager" "$opts" "$package"
done

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	echo "stow $folder"
	stow -D $folder
	stow $folder
done
popd
