#!/bin/bash
vcprompturl=https://raw.githubusercontent.com/djl/vcprompt/master/bin/vcprompt
nvm=https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh

ln -sf $PWD/bashconfig ~/.bash_aliases
ls -l ~/.bash_aliases
ln -sf $PWD/vimrc ~/.vimrc
ls -l ~/.vimrc
ln -sf $PWD/bashrc ~/.bashrc
ls -l ~/.bashrc
ln -sf $PWD/alacritty ~/.alacritty.yml
ls -l ~/.alacritty.yml
ln -sf $PWD/tmux.conf ~/.tmux.conf
ls -l ~/.tmux.conf

# Installing vcprompt - Version Control Info
mkdir -p ~/bin
curl -sL ${vcprompturl} > ~/bin/vcprompt 
chmod 755 ~/bin/vcprompt

# Installing nvm
curl -o- ${nvm} | bash
nvm install --lts

# Installing emojis
sudo pacman -S noto-fonts-emoji

# Installing fira code
sudo pacman -S ttf-fira-code

# Installing Yay
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && cd . &&  rm -rf yay
